version: "3"
services:
  google_api_newman:
    image: postman/newman:alpine
    environment:
      - API_KEY
    volumes:
      - ./postman:/etc/newman
    command:
      run /etc/newman/Google_Civic_Information_API.postman_collection.json
      --env-var API_KEY=${API_KEY}
  graphql_newman:
    image: postman/newman:alpine
    depends_on:
      - graphql-api-spr-boot
    volumes:
      - ./postman:/etc/newman
    command:
      run /etc/newman/Civic_Information_GraphQL.postman_collection.json
      -e /etc/newman/docker-compose-local.postman_environment.json
      --env-var API_KEY=${API_KEY}

  graphql-api-spr-boot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY
    ports:
      - 8080:8080

